const sensationalWords = [
    'shocking', 'amazing', 'incredible', 'unbelievable', 'miracle', 'secret', 'conspiracy',
    'they don\'t want you to know', 'breakthrough', 'bombshell', 'stunning', 'jaw-dropping', 
    'mind-blowing', 'explosive', 'revolutionary', 'bizarre', 'outrageous', 'controversial', 
    'exposed', 'you won\'t believe', 'game-changer', 'hidden truth', 'life-changing', 
    'forbidden', 'mystery', 'scandalous', 'wild', 'terrifying', 'must-see', 'unmasking', 
    'the dark side of', 'once in a lifetime', 'insane', 'next-level', 'chaotic', 'disturbing', 
    'earth-shattering', 'eye-opening', 'dangerous', 'horrifying', 'catastrophic', 
    'world-ending', 'legendary', 'too good to be true', 'never-before-seen', 'the truth behind', 
    'history in the making', 'you are being lied to', 'secrets revealed', 'mind control', 
    'trapped', 'wake up', 'urgent', 'emergency', 'leaked', 'world will never be the same', 
    'vanished', 'uncovered', 'mysterious', 'groundbreaking', 'freaky', 'twisted', 'terrifying', 
    'you have been warned', 'conclusive proof', 'biggest lie ever', 'history rewritten', 
    'cover-up', 'banned', 'censored', 'forbidden knowledge', 'scary', 'panic', 'the most', 
    'sweeping changes', 'hidden dangers', 'unprecedented', 'never told before', 'unfiltered', 
    'uncensored', 'mind games', 'shockwave', 'sensational', 'breaking news', 'deception', 
    'manipulation', 'it’s happening', 'ultimate truth', 'reality check', 'paranormal', 
    'sinister', 'dark forces', 'fateful', 'deadly', 'mystical', 'prophecy', 'untold', 
    'fearless expose', 'corrupt', 'maniacal', 'dangerous game', 'epic fail', 'devastating',
    'unforgivable', 'tragedy', 'chaos', 'game over', 'hidden agenda', 'wake-up call',
    'earth-shaking', 'game changer', 'smoking gun', 'blockbuster', 'apocalyptic',
    'major reveal', 'insider information', 'exclusive', 'shadow government', 'trolled',
    'crushed', 'destroyed', 'elite', 'global elite', 'shadow powers',
    'globalist agenda', 'new world order', 'deep state', 'cabal', 'illuminati',
    'mainstream media won\'t tell you', 'operation', 'mainstream media lies',
    'they\'re all lying', 'this is the real truth', 'deleting this soon',
    'riots', 'crackdown', 'absolute power', 'experts shocked', 'they can\'t believe',
    'lost all control', 'melting down', 'breaking point', 'gone viral',
    'absolutely decimated', 'backfired spectacularly', 'nightmarish',
    'red alert', 'alarm bells', 'skyrocketing', 'plummeting', 'erupting',
    'exploding', 'going off the rails', 'imploding', 'beyond repair',
    'you\'re being played', 'played like a fiddle', 'plandemic', 'scamdemic',
    'false flag', 'staged', 'coordinated attack', 'they\'re coming for you',
    'weaponized', 'manufactured crisis', 'perfect storm', 'powder keg',
    'this changes everything', 'everything you know is wrong', 'this explains everything',
    'connecting the dots', 'follow the money', 'stop the steal', 'rigged',
    'making a killing', 'psychological operation', 'psyop', 'brainwashing',
    'mind control', 'predictive programming', 'constitutional crisis',
    'constitutional emergency', 'silent majority', 'silent war', 'information war'
];

const scientificWords = [
    'study', 'research', 'evidence', 'data', 'analysis', 'experiment', 'hypothesis', 
    'conclusion', 'findings', 'method', 'theory', 'variables', 'peer-reviewed', 
    'empirical', 'quantitative', 'qualitative', 'scientific method', 'statistical significance', 
    'control group', 'sample size', 'correlation', 'causation', 'probability', 'replication', 
    'modeling', 'simulation', 'algorithm', 'hypothesis testing', 'meta-analysis', 'double-blind',
    'placebo', 'randomized', 'systematic review', 'longitudinal study', 'biotechnology', 
    'genomics', 'neuroscience', 'cognitive science', 'astrophysics', 'nanotechnology', 
    'quantum mechanics', 'particle physics', 'thermodynamics', 'entropy', 'mutation', 
    'evolution', 'biodiversity', 'photosynthesis', 'molecular biology', 'CRISPR', 'DNA sequencing', 
    'epigenetics', 'synthetic biology', 'ecosystem', 'climate change', 'atmospheric science', 
    'geophysics', 'seismology', 'paleontology', 'fossil record', 'plate tectonics', 
    'dark matter', 'dark energy', 'gravitational waves', 'relativity', 'black hole', 
    'exoplanet', 'supernova', 'antimatter', 'biochemistry', 'enzymes', 'cellular respiration', 
    'gene expression', 'microbiology', 'pathogen', 'antibody', 'virology', 'bacteriology', 
    'immunology', 'pandemic', 'epidemiology', 'public health', 'vaccine', 'clinical trials', 
    'toxicology', 'neurotransmitter', 'synapse', 'electromagnetism', 'wave-particle duality', 
    'Schrödinger’s equation', 'string theory', 'catalyst', 'chemical reaction', 'isotope', 
    'half-life', 'oxidation', 'polymer', 'nanoparticle', 'biomimicry', 'synthetic materials', 
    'photonics', 'spectroscopy', 'mass spectrometry', 'X-ray crystallography', 'radioactivity', 
    'geology', 'mineralogy', 'volcanology', 'oceanography', 'cryosphere', 'biosphere', 
    'biogeochemistry', 'cybernetics', 'biostatistics', 'ecotoxicology', 'biophysics', 
    'aerodynamics', 'fluid dynamics', 'robotics', 'machine learning', 'artificial intelligence', 
    'neural networks', 'bioinformatics', 'genetic engineering', 'astrobiology', 'terraforming',
    'quantum entanglement', 'quantum computing', 'superposition', 'allele frequency',
    'phylogeny', 'taxonomy', 'phenotype', 'genotype', 'transcription factors',
    'neural plasticity', 'neurogenesis', 'ion channels', 'action potential',
    'mitochondrial DNA', 'ribosomal RNA', 'apoptosis', 'cellular division',
    'meiosis', 'mitosis', 'endoplasmic reticulum', 'golgi apparatus',
    'covalent bonds', 'valence electron', 'redox reaction', 'stoichiometry',
    'nucleosynthesis', 'stellar fusion', 'magnetosphere', 'paleomagnetic',
    'cryovolcanism', 'hydrothermal vent', 'extremophile', 'biogeography',
    'phylogeography', 'ethology', 'behavioral ecology', 'circadian rhythm',
    'chronobiology', 'psychophysics', 'operant conditioning', 'neurochemistry',
    'pharmacodynamics', 'pharmacokinetics', 'pharmacogenomics', 'bioavailability',
    'bioinformatics', 'computational biology', 'systems biology', 'synthetic genomics',
    'genetic algorithm', 'neural network architecture', 'convolutional neural network',
    'recursive neural network', 'backpropagation', 'gradient descent',
    'reinforcement learning', 'unsupervised learning', 'supervised learning',
    'deep learning', 'natural language processing', 'computer vision',
    'edge computing', 'quantum supremacy', 'post-quantum cryptography',
    'differential equation', 'partial differential equation', 'vector calculus',
    'fourier transform', 'laplace transform', 'eigenvalues', 'eigenvectors',
    'linear algebra', 'matrix multiplication', 'tensor analysis', 'graph theory',
    'combinatorial optimization', 'stochastic process', 'markov chain',
    'bayesian inference', 'maximum likelihood estimation', 'regression analysis',
    'multivariate analysis', 'principal component analysis', 'cluster analysis',
    'structural equation modeling', 'time series analysis', 'bootstrap sampling',
    'confidence interval', 'null hypothesis', 'alternative hypothesis',
    'statistical power', 'effect size', 'meta-regression', 'forest plot'
];

const positiveWords = [
    'awesome', 'amazing', 'brilliant', 'fantastic', 'excellent', 'wonderful', 'fabulous', 'superb', 'spectacular', 'remarkable', 
    'outstanding', 'phenomenal', 'magnificent', 'incredible', 'extraordinary', 'breathtaking', 'stunning', 'unbelievable', 'jaw-dropping', 'mind-blowing',
    'joyful', 'happy', 'cheerful', 'delightful', 'ecstatic', 'elated', 'euphoric', 'radiant', 'grateful', 'content', 
    'blissful', 'serene', 'tranquil', 'peaceful', 'cheery', 'exuberant', 'glad', 'mirthful', 'upbeat', 'lively',
    'kind', 'compassionate', 'caring', 'generous', 'thoughtful', 'empathetic', 'considerate', 'helpful', 'selfless', 'benevolent', 
    'charitable', 'heartwarming', 'nurturing', 'gentle', 'forgiving', 'sympathetic', 'supportive', 'altruistic', 'encouraging', 'gracious',
    'successful', 'accomplished', 'achieved', 'victorious', 'prosperous', 'thriving', 'empowered', 'capable', 'resilient', 'determined', 
    'unstoppable', 'goal-oriented', 'ambitious', 'motivated', 'inspired', 'passionate', 'driven', 'focused', 'disciplined', 'committed',
    'loving', 'romantic', 'devoted', 'affectionate', 'caring', 'trusting', 'faithful', 'companionate', 'soulmate', 'intimate', 
    'cherished', 'adored', 'beloved', 'tender', 'heartfelt', 'devoted', 'harmonious', 'united', 'supportive', 'loyal',
    'optimistic', 'hopeful', 'confident', 'reassuring', 'bright', 'uplifting', 'inspiring', 'motivational', 'encouraging', 'cheerful', 
    'enthusiastic', 'spirited', 'buoyant', 'positive', 'vivacious', 'effervescent', 'invigorating', 'stimulating', 'refreshing', 'empowering',
    'brilliant', 'ingenious', 'insightful', 'wise', 'thoughtful', 'innovative', 'visionary', 'creative', 'original', 'artistic', 
    'imaginative', 'resourceful', 'perceptive', 'intuitive', 'intellectual', 'inspiring', 'pioneering', 'revolutionary', 'bright-minded', 'clever',
    'strong', 'courageous', 'bold', 'fearless', 'valiant', 'brave', 'resilient', 'tenacious', 'determined', 'unwavering', 
    'steadfast', 'indomitable', 'unstoppable', 'heroic', 'persistent', 'gutsy', 'daring', 'adventurous', 'undaunted', 'unshakable',
    'healthy', 'vibrant', 'energetic', 'fit', 'robust', 'rejuvenated', 'refreshed', 'restored', 'balanced', 'nourished', 
    'whole', 'pure', 'detoxified', 'healing', 'revitalized', 'active', 'agile', 'dynamic', 'flourishing', 'invigorated',
    'blooming', 'lush', 'verdant', 'majestic', 'serene', 'tranquil', 'peaceful', 'picturesque', 'radiant', 'golden', 
    'glowing', 'heavenly', 'breezy', 'crisp', 'fresh', 'pristine', 'soothing', 'harmonious', 'sparkling', 'illuminated',
    'fortunate', 'blessed', 'lucky', 'prosperous', 'wealthy', 'bountiful', 'abundant', 'rich', 'thriving', 'rewarding', 
    'windfall', 'serendipitous', 'flourishing', 'opportune', 'golden opportunity', 'favorable', 'booming', 'success-laden', 'fruitful', 'rewarding',
    'flourishing', 'resplendent', 'praiseworthy', 'commendable', 'meritorious',
    'sublime', 'transcendent', 'ethical', 'principled', 'virtuous', 'honorable',
    'respectful', 'dignified', 'genuine', 'authentic', 'integrity', 'respectable',
    'acclaimed', 'esteemed', 'revered', 'venerated', 'exalted', 'elevated',
    'marvelous', 'wondrous', 'enchanting', 'captivating', 'mesmerizing',
    'fascinating', 'enthralling', 'spellbinding', 'bewitching', 'alluring',
    'attractive', 'pleasing', 'favorable', 'gratifying', 'satisfying',
    'rewarding', 'fulfilling', 'engaging', 'compelling', 'conducive',
    'promising', 'auspicious', 'propitious', 'beneficial', 'advantageous',
    'fortunate', 'miraculous', 'proficient', 'adept', 'masterful', 'skillful',
    'accomplished', 'diligent', 'prudent', 'knowledgeable', 'insightful',
    'rational', 'reasonable', 'logical', 'coherent', 'sound', 'sensible',
    'balanced', 'pragmatic', 'practical', 'effective', 'efficacious',
    'productive', 'constructive', 'improvement', 'enhancement', 'enrichment',
    'authentic', 'genuine', 'refined', 'exquisite', 'elegant', 'graceful',
    'sophisticated', 'tasteful', 'discerning', 'perceptive', 'astute',
    'appreciative', 'responsive', 'attentive', 'cooperative', 'accommodating',
    'receptive', 'open-minded', 'tolerant', 'accepting', 'inclusive',
    'respectful', 'courteous', 'cordial', 'amiable', 'affable', 'congenial',
    'wholesome', 'nourishing', 'nutritious', 'beneficial', 'therapeutic'
];

const negativeWords = [
    'bad', 'terrible', 'awful', 'horrible', 'poor', 'negative', 'worst', 'failure', 
    'failed', 'inadequate', 'inferior', 'wrong', 'mistake', 'problematic', 'dangerous', 
    'threat', 'crisis', 'disaster', 'catastrophe', 'tragic', 'sad', 'angry', 'hostile', 
    'violent', 'painful', 'suffering', 'depressing', 'hopeless', 'devastating', 'ruin', 
    'destructive', 'fatal', 'fearful', 'dreadful', 'appalling', 'horrifying', 'grief', 
    'miserable', 'disgrace', 'shameful', 'scandalous', 'corrupt', 'exploitative', 
    'oppressive', 'abusive', 'discriminatory', 'prejudiced', 'biased', 'hateful', 'resentful', 
    'bitter', 'jealous', 'toxic', 'manipulative', 'deceitful', 'dishonest', 'treacherous', 
    'betrayal', 'abandonment', 'isolation', 'loneliness', 'despair', 'regret', 'loss', 
    'defeat', 'downfall', 'bankruptcy', 'meltdown', 'collapse', 'ruined', 'doomed', 'bleak', 
    'unfortunate', 'accident', 'calamity', 'chaotic', 'tumultuous', 'unstable', 'fraudulent', 
    'malicious', 'heinous', 'atrocious', 'vile', 'slanderous', 'insulting', 'offensive', 
    'degrading', 'humiliating', 'disrespectful', 'intolerable', 'unfair', 'harsh', 'rigid', 
    'oppressive', 'brutal', 'ruthless', 'merciless', 'unjust', 'criminal', 'illegal', 
    'illicit', 'scam', 'deception', 'treason', 'violation', 'trespassing', 'abnormal', 
    'disturbing', 'unnatural', 'repulsive', 'disgusting', 'nauseating', 'putrid', 'vulgar', 
    'cruel', 'barbaric', 'savage', 'monster', 'beastly', 'horrendous', 'wicked', 'sinister', 
    'malevolent', 'nefarious', 'malignant', 'fiendish', 'demonic', 'cursed', 'darkness', 
    'plague', 'infestation', 'epidemic', 'pandemic', 'famine', 'starvation', 'homeless', 
    'destitute', 'bankrupt', 'unemployed', 'penniless', 'helpless', 'weak', 'vulnerable', 
    'exhausted', 'burnout', 'overwhelmed', 'burden', 'stress', 'pressure', 'anxiety', 
    'panic', 'fear', 'paranoia', 'nightmare', 'hysteria', 'delirium', 'insanity', 'madness', 
    'deranged', 'psychotic', 'unstable', 'schizophrenic', 'paralyzed', 'crippled', 'disabled', 
    'deformed', 'mutated', 'horrid', 'hideous', 'ghastly', 'grotesque', 'dismal', 'gloomy', 
    'shadowy', 'sinister', 'foreboding', 'menacing', 'ominous', 'danger', 'peril', 'precarious', 
    'volatile', 'deadly', 'lethal', 'murderous', 'suicidal', 'homicidal', 'execution', 
    'massacre', 'genocide', 'war', 'battle', 'bloodshed', 'torture', 'torment', 'agony', 
    'anguish', 'pain', 'injury', 'wound', 'scarred', 'bruised', 'broken', 'shattered', 
    'wrecked', 'destroyed', 'deteriorated', 'corroded', 'eroded', 'polluted', 'contaminated', 
    'decayed', 'rotten', 'infested', 'diseased', 'infected', 'sick', 'ailing', 'dying', 
    'dead', 'corpse', 'cadaver', 'funeral', 'mourning', 'sorrow', 'weeping', 'crying', 
    'screaming', 'yelling', 'ranting', 'raging', 'furious', 'fuming', 'boiling', 'exploding', 
    'detonated', 'eruption', 'earthquake', 'hurricane', 'tornado', 'tsunami', 'flood', 
    'drought', 'blizzard', 'fire', 'inferno', 'burning', 'charred', 'scorched', 'ashes', 
    'annihilation', 'obliteration', 'eradication', 'extermination', 'execution', 'guillotine', 
    'lynching', 'beheading', 'assassination', 'bombing', 'terrorism', 'hostage', 'kidnapping', 
    'ransom', 'trafficking', 'enslavement', 'abduction', 'extortion', 'blackmail', 'corruption', 
    'bribery', 'embezzlement', 'scandal', 'collusion', 'conspiracy', 'manipulation', 'brainwashing',
    'despicable', 'reprehensible', 'contemptible', 'deplorable', 'inexcusable',
    'unforgivable', 'intolerable', 'unbearable', 'insufferable', 'unspeakable',
    'unethical', 'immoral', 'depraved', 'perverted', 'degenerate', 'debased',
    'debauched', 'dissolute', 'unprincipled', 'iniquitous', 'sinful', 'malicious',
    'spiteful', 'vindictive', 'venomous', 'vitriolic', 'acrimonious', 'belligerent',
    'contemptuous', 'demeaning', 'disparaging', 'disrespectful', 'ridiculing',
    'mocking', 'taunting', 'belittling', 'condescending', 'patronizing',
    'denigrating', 'defaming', 'slandering', 'calumniating', 'libeling',
    'smearing', 'defiling', 'contaminating', 'tainting', 'defacing',
    'profaning', 'desecrating', 'violating', 'transgressing', 'defiling',
    'depressing', 'disheartening', 'discouraging', 'dispiriting', 'deflating',
    'demoralizing', 'disheartening', 'disenchanting', 'disillusioning',
    'disappointing', 'frustrating', 'disorienting', 'dismaying', 'distressing',
    'disturbing', 'unsettling', 'perturbing', 'alarming', 'frightening',
    'terrifying', 'petrifying', 'horrific', 'nasty', 'foul', 'loathsome',
    'repugnant', 'abhorrent', 'detestable', 'sickening', 'nauseating',
    'irrelevant', 'meaningless', 'insignificant', 'trivial', 'frivolous',
    'pointless', 'futile', 'fruitless', 'worthless', 'useless', 'ineffective',
    'ineffectual', 'incompetent', 'inept', 'unprofessional', 'substandard',
    'mediocre', 'inadequate', 'deficient', 'faulty', 'flawed', 'impaired'
];

const leftBiasWords = [
    'progressive', 'liberal', 'secular', 'leftist', 'social justice', 
    'welfare state', 'equality', 'reservation', 'socialism', 'communism', 
    'income redistribution', 'government intervention', 'free education', 
    'public healthcare', 'universal basic income', 'workers rights', 'labor rights', 
    'minimum wage', 'livelihood security', 'agrarian rights', 'land reforms', 
    'tenant rights', 'tribal rights', 'dalit empowerment', 'bahujan politics', 
    'anti-caste', 'affirmative action', 'social equity', 'social movements', 
    'climate action', 'environmental justice', 'sustainable development', 
    'renewable energy', 'carbon tax', 'green policies', 'climate crisis', 
    'net zero emissions', 'gender justice', 'feminism', 'LGBTQ+ rights', 
    'gender equality', 'gender pay gap', 'equal rights', 'civil liberties', 
    'hate speech laws', 'freedom of expression', 'minority rights', 
    'religious pluralism', 'anti-hindutva', 'anti-majoritarianism', 
    'free speech protection', 'human rights', 'prison reform', 'police reform', 
    'defund the police', 'criminal justice reform', 'rehabilitation programs', 
    'anti-fascism', 'anti-communalism', 'anti-authoritarianism', 'media freedom', 
    'press freedom', 'academic freedom', 'decolonization', 'subaltern studies', 
    'historical revisionism', 'secular values', 'constitutional morality', 
    'democratic socialism', 'vote bank politics', 'state welfare', 'public sector', 
    'socialized education', 'right to education', 'right to food', 'free ration', 
    'poverty alleviation', 'anti-displacement', 'land back', 'indigenous rights', 
    'tribal empowerment', 'social justice warrior', 'political correctness', 
    'woke culture', 'cultural appropriation', 'progressive taxation', 
    'tax the rich', 'wealth redistribution', 'anti-capitalism', 'big pharma regulation', 
    'anti-corporate', 'public utilities', 'food security', 'universal pension', 
    'housing for all', 'affordable housing', 'right to shelter', 'gender fluid', 
    'gender neutral', 'preferred pronouns', 'pride rights', 'decriminalization of homosexuality', 
    'marriage equality', 'hate crime legislation', 'reproductive rights', 'pro-choice', 
    'menstrual equity', 'reproductive healthcare', 'comprehensive sex education', 
    'Muslim rights', 'Dalit rights', 'backward class upliftment', 'anti-Brahminism', 
    'anti-upper caste hegemony', 'abolish caste', 'abolish manual scavenging', 
    'dravidian movement', 'jati system critique', 'Naxalism discussion', 
    'civil resistance', 'radical democracy', 'grassroots activism', 
    'public protest', 'student activism', 'anti-colonial resistance', 
    'revolutionary politics', 'public transportation advocacy', 'economic stimulus', 
    'free higher education', 'debt forgiveness', 'progressive governance', 
    'universal healthcare', 'Medicaid expansion', 'state intervention', 
    'abolish billionaires', 'mutual aid', 'community organizing', 
    'international solidarity', 'anti-imperialism', 'anti-privatization', 
    'pro-public sector', 'government subsidies', 'basic income scheme', 
    'anti-surveillance state', 'digital rights', 'internet freedom', 
    'net neutrality', 'big tech regulation', 'anti-corporate lobbying', 
    'political accountability', 'wealth tax', 'abolish sedition law', 
    'restore article 370', 'anti-caa', 'free speech activism', 'judicial activism',
    'democratic values', 'inclusivity', 'diversity training', 'critical race theory',
    'systemic racism', 'structural inequality', 'institutionalized discrimination',
    'power structures', 'privilege awareness', 'microaggressions', 'safe spaces',
    'trigger warnings', 'cultural sensitivity', 'intersectionality',
    'marginalized communities', 'underrepresented groups', 'lived experience',
    'decolonizing curriculum', 'non-binary', 'trans rights', 'they/them pronouns',
    'gender affirmation', 'gender-affirming care', 'reproductive autonomy',
    'bodily autonomy', 'abortion access', 'planned parenthood', 'defund police',
    'community oversight', 'prison abolition', 'decriminalization', 'anti-war',
    'pacifism', 'military spending cuts', 'diplomatic solutions',
    'peace negotiations', 'global cooperation', 'international law',
    'un peacekeeping', 'humanitarian intervention', 'open borders',
    'sanctuary cities', 'immigrant rights', 'path to citizenship', 'dreamers',
    'undocumented immigrants', 'refugee resettlement', 'asylum seekers',
    'universal healthcare', 'medicare for all', 'single-payer system',
    'public option', 'affordable care act', 'food stamps', 'housing subsidies',
    'eviction moratorium', 'rent control', 'tuition-free college',
    'student loan forgiveness', 'progressive taxation', 'wealth tax',
    'billionaire tax', 'capital gains tax', 'estate tax', 'corporate regulations',
    'wall street regulations', 'consumer protections', 'labor organizing',
    'unions', 'collective bargaining', 'workers cooperatives', 'fair trade',
    'climate justice', 'environmental justice', 'green new deal',
    'renewable transition', 'carbon neutrality', 'climate reparations',
    'indigenous land rights', 'vaccine equity', 'equitable healthcare access',
    'universal basic income', 'living wage', 'guaranteed income', 'wealth redistribution',
    'democratic socialism', 'eco-socialism', 'anti-fascism', 'anti-racism'
];

const rightBiasWords = [
    'hindutva', 'bjp', 'modi', 'rss', 'sangh', 
    'nationalist', 'bharat first', 'sanatan dharma', 'hindu rashtra', 
    'deshbhakt', 'nation first', 'cultural nationalism', 'development', 
    'self-reliance', 'atmanirbhar bharat', 'vocal for local', 
    'swadeshi', 'ram rajya', 'article 370', 'triple talaq ban', 
    'caa', 'uniform civil code', 'population control', 'ghar wapsi', 
    'love jihad', 'gau raksha', 'cow protection', 'temple restoration', 
    'vedic values', 'traditional family values', 'bharatiya sanskriti', 
    'ayodhya', 'ram mandir', 'kashmir issue', 'pakistan-sponsored terror', 
    'surgical strike', 'national security', 'strong borders', 
    'border security', 'chinese aggression', 'foreign policy hawks', 
    'make in india', 'digital india', 'bullet train', 'infrastructure boost', 
    'economic reforms', 'gst success', 'demonetization', 'black money', 
    'anti-corruption', 'strong leadership', 'modi hai to mumkin hai', 
    'double engine sarkar', 'pro-business', 'ease of doing business', 
    'corporate tax cut', 'privatization', 'economic nationalism', 
    'reservation review', 'meritocracy', 'muslim appeasement', 
    'vote bank politics', 'anti-separatism', 'nation over religion', 
    'love for the motherland', 'anti-urban naxals', 'anti-left', 
    'marxist agenda', 'tukde tukde gang', 'radical left', 'anti-woke', 
    'media bias', 'godi media', 'presstitute', 'leftist propaganda', 
    'congress mukt bharat', 'dynasty politics', 'secularism hypocrisy', 
    'anti-pseudo secularism', 'pseudo-liberals', 'liberal mafia', 
    'intellectual elite', 'deep state india', 'jnu propaganda', 
    'anti-national', 'desh ke gaddar', 'traitors of the nation', 
    'national pride', 'bharat mata ki jai', 'vande mataram', 
    'jai shri ram', 'har har mahadev', 'religious freedom', 
    'uniformity in laws', 'free market', 'pro-business reforms', 
    'individual liberty', 'anti-communism', 'anti-socialism', 
    'anti-feminism', 'gender ideology', 'traditional gender roles', 
    'anti-lgbt propaganda', 'caste-based politics', 'one nation one election', 
    'one nation one tax', 'election integrity', 'voter id laws', 
    'anti-reservation', 'right to life', 'anti-abortion', 'nuclear family values', 
    'pro-army', 'armed forces pride', 'police empowerment', 
    'strong governance', 'strict laws', 'anti-terror laws', 'death penalty for rapists', 
    'population control laws', 'strict punishment for criminals', 
    'fake news propaganda', 'leftist ecosystem', 'cultural heritage protection', 
    'sanskrit revival', 'temple rights', 'religious rights', 
    'anti-romeo squads', 'love for hindi', 'hindi imposition', 
    'national unity', 'patriotism over politics',
    'fiscal responsibility', 'balanced budget', 'spending cuts', 'tax relief',
    'job creators', 'free enterprise', 'deregulation', 'limited government',
    'states rights', 'constitutional originalism', 'strict constructionism',
    'constitutional conservatism', 'second amendment rights', 'gun ownership',
    'stand your ground', 'castle doctrine', 'law and order', 'tough on crime',
    'mandatory minimums', 'police support', 'blue lives matter', 'border security',
    'illegal immigration', 'illegal aliens', 'border wall', 'deportation',
    'extreme vetting', 'travel ban', 'america first', 'economic nationalism',
    'trade protectionism', 'tariffs', 'military strength', 'strong military',
    'defense spending', 'national defense', 'patriotism', 'flag respect',
    'american exceptionalism', 'western civilization', 'judeo-christian values',
    'religious liberty', 'religious freedom', 'pro-life', 'right to life',
    'sanctity of life', 'traditional marriage', 'family values', 'parental rights',
    'school choice', 'charter schools', 'voucher system', 'homeschooling',
    'anti-critical race theory', 'merit-based', 'color-blind society',
    'anti-affirmative action', 'self-reliance', 'personal responsibility',
    'bootstraps', 'work ethic', 'welfare reform', 'entitlement reform',
    'market solutions', 'privatization', 'rugged individualism', 'big government',
    'government overreach', 'regulatory burden', 'tax burden', 'nanny state',
    'big tech censorship', 'cancel culture', 'political correctness',
    'free speech rights', 'anti-socialism', 'anti-marxism', 'radical left',
    'liberal media', 'fake news', 'media bias', 'coastal elites',
    'silent majority', 'main street', 'real america', 'heartland values',
    'rural values', 'american sovereignty', 'energy independence',
    'fossil fuels', 'clean coal', 'oil drilling', 'american energy',
    'pro-business', 'job growth', 'economic freedom', 'opportunity zones',
    'school prayer', 'faith-based initiatives', 'culture war', 'traditional values',
    'anti-globalism', 'anti-establishment', 'drain the swamp', 'deep state'
];
const stopWords = [
    'the', 'and', 'a', 'to', 'of', 'in', 'is', 'it', 'that', 'was', 'for', 
    'on', 'with', 'as', 'by', 'at', 'an', 'be', 'this', 'which', 'or', 
    'from', 'but', 'not', 'are', 'were', 'has', 'have', 'had', 'can', 
    'will', 'would', 'should', 'could', 'about', 'into', 'up', 'out', 
    'if', 'then', 'so', 'no', 'yes', 'do', 'does', 'did', 'just', 'like', 
    'over', 'under', 'more', 'less', 'very', 'some', 'any', 'all', 'most', 
    'many', 'few', 'such', 'only', 'own', 'same', 'other', 'than', 'too', 
    'much', 'how', 'when', 'where', 'why', 'what', 'who', 'whom', 'whose', 
    'which', 'because', 'while', 'though', 'although', 'before', 'after', 
    'during', 'between', 'within', 'without', 'against', 'through', 
    'each', 'every', 'either', 'neither', 'both', 'one', 'two', 'three', 
    'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten'
  ];
  const fakePhrases = [
    'they don\'t want you to know',
    'what the media isn\'t telling you',
    'doctors hate this',
    'the truth about',
    'what they\'re hiding',
    'what the government doesn\'t want you to know',
    'big pharma doesn\'t want you to know',
    'share before it\'s deleted',
    'the mainstream media won\'t report this',
    'hidden agenda exposed',
    'shocking discovery',
    'you won\'t believe',
    'this will change everything',
    'wake up before it\'s too late',
    'the secret they don\'t want you to know',
    'this is what really happened',
    'proof they\'re lying to you',
    'the untold story',
    'what experts won\'t tell you',
    'this changes everything',
    'the cure they don\'t want you to find',
    'exposed: the truth about',
    'this is being covered up',
    'you\'re being lied to',
    'the hidden truth',
    'this is what they don\'t want you to see',
    'the real reason behind',
    'this is why they\'re scared',
    'the shocking truth',
    'this will blow your mind',
    'the biggest cover-up in history',
    'what they don\'t want you to hear',
    'this is what they\'re hiding',
    'the truth they don\'t want you to know',
    'this is why they\'re panicking',
    'the secret behind',
    'this is what they\'re afraid of',
    'the real story behind',
    'this is being suppressed',
    'the truth about the elites',
    'this is what they\'re not telling you',
    'the conspiracy exposed',
    'this is why they\'re lying',
    'the hidden agenda',
    'this is what they\'re covering up',
    'the untold truth',
    'this is why they\'re desperate',
    'the secret they\'re keeping',
    'this is what they don\'t want you to believe',
    'the truth about the system',
    'this is why they\'re hiding it',
    'the real agenda behind',
    'this is what they\'re not showing you',
    'the truth about the media',
    'this is why they\'re scared of you',
    'the hidden truth about',
    'this is what they\'re not telling the public',
    'the real reason they\'re lying',
    'this is why they\'re panicking about',
    'the shocking truth about',
    'this is what they\'re afraid you\'ll find out',
    'the secret they\'re hiding from you',
    'this is what they don\'t want you to uncover',
    'the truth about the establishment',
    'this is why they\'re suppressing it',
    'the real story they don\'t want you to know',
    'this is what they\'re not reporting',
    'the truth about the deep state',
    'this is why they\'re censoring it',
    'the hidden truth they don\'t want you to see',
    'this is what they\'re not admitting',
    'the real reason they\'re scared',
    'this is why they\'re trying to silence you',
    'the truth about the globalists',
    'this is what they\'re not revealing',
    'the hidden agenda they don\'t want you to know',
    'this is why they\'re panicking so much',
    'the truth about the elites\' plan',
    'this is what they\'re not telling anyone',
    'the real reason they\'re hiding it',
    'this is why they\'re so desperate',
    'the truth about the secret society',
    'this is what they\'re not showing the world',
    'the hidden truth about the system',
    'this is why they\'re lying to everyone',
    'the real agenda they don\'t want you to know',
    'this is what they\'re not saying',
    'the truth about the hidden plan',
    'this is why they\'re scared of the truth',
    'the shocking truth they don\'t want you to know',
    'this is what they\'re not telling the masses',
    'the real reason they\'re covering it up',
    'this is why they\'re so afraid',
    'the truth about the hidden agenda',
    'this is what they\'re not letting you see',
    'the real story they\'re hiding',
    'this is why they\'re panicking right now',
    'the truth about the secret plan',
    'this is what they\'re not telling the people',
    'the hidden truth they\'re afraid of',
    'this is why they\'re suppressing the truth',
    'the real reason they\'re lying to you',
    'this is what they\'re not showing anyone',
    'the truth about the hidden conspiracy',
    'this is why they\'re scared of the facts',
    'the shocking truth they\'re hiding',
    'this is what they\'re not admitting to the public',
    'the real agenda they\'re afraid of',
    'this is why they\'re trying to silence the truth',
    'the truth about the hidden elites',
    'this is what they\'re not revealing to the world',
    'the hidden agenda they\'re scared of',
    'this is why they\'re panicking so much right now',
    'the truth about the secret plan they\'re hiding',
    'this is what they\'re not telling the world',
    'the real reason they\'re scared of the truth',
    'this is why they\'re so desperate to hide it',
    'the truth about the hidden conspiracy they\'re afraid of',
    'this is what they\'re not letting anyone see',
    'the real story they\'re hiding from the public',
    'this is why they\'re panicking about the truth',
    'the truth about the secret agenda they\'re hiding',
    'this is what they\'re not telling the people about',
    'the hidden truth they\'re scared of being exposed',
    'this is why they\'re suppressing the facts',
    'the real reason they\'re lying to everyone about',
    'this is what they\'re not showing the masses',
    'the truth about the hidden plan they\'re afraid of',
    'this is why they\'re scared of the truth coming out',
    'the shocking truth they\'re hiding from the world',
    'this is what they\'re not admitting to anyone',
    'the real agenda they\'re afraid of being exposed',
    'this is why they\'re trying to silence the facts',
    'the truth about the hidden elites\' plan',
    'this is what they\'re not revealing to anyone',
    'the hidden agenda they\'re scared of being exposed',
    'this is why they\'re panicking so much about the truth',
    'the truth about the secret plan they\'re hiding from the public',
    'this is what they\'re not telling the world about',
    'the real reason they\'re scared of the facts coming out',
    'this is why they\'re so desperate to hide the truth',
    'the truth about the hidden conspiracy they\'re afraid of being exposed',
    'this is what they\'re not letting anyone know about',
    'the real story they\'re hiding from the masses',
    'this is why they\'re panicking about the facts coming out',
    'the truth about the secret agenda they\'re hiding from the world',
    'this is what they\'re not telling the people about the truth',
    'the hidden truth they\'re scared of being revealed',
    'this is why they\'re suppressing the truth about the facts',
    'the real reason they\'re lying to everyone about the truth',
    'this is what they\'re not showing the masses about the facts',
    'the truth about the hidden plan they\'re afraid of being revealed',
    'this is why they\'re scared of the truth being exposed',
    'the shocking truth they\'re hiding from the public about the facts',
    'this is what they\'re not admitting to anyone about the truth',
    'the real agenda they\'re afraid of being revealed to the world',
    'this is why they\'re trying to silence the truth about the facts',
    'the truth about the hidden elites\' plan they\'re afraid of being exposed',
    'this is what they\'re not revealing to anyone about the truth',
    'the hidden agenda they\'re scared of being revealed to the public',
    'this is why they\'re panicking so much about the truth being exposed',
    'the truth about the secret plan they\'re hiding from the masses',
    'this is what they\'re not telling the world about the truth',
    'the real reason they\'re scared of the facts being revealed',
    'this is why they\'re so desperate to hide the truth from the public',
    'the truth about the hidden conspiracy they\'re afraid of being revealed',
    'this is what they\'re not letting anyone know about the truth',
    'the real story they\'re hiding from the masses about the facts',
    'this is why they\'re panicking about the facts being revealed to the public'
];

const sourceReputationData = {
    // Highly trusted sources
    'reuters.com': { reliability: 95, bias: -2, factChecking: 5, editorialStandards: 5, transparency: 5 },
    'apnews.com': { reliability: 94, bias: 0, factChecking: 5, editorialStandards: 5, transparency: 5 },
    'bbc.com': { reliability: 92, bias: -5, factChecking: 5, editorialStandards: 5, transparency: 4 },
    'bbc.co.uk': { reliability: 92, bias: -5, factChecking: 5, editorialStandards: 5, transparency: 4 },
    'npr.org': { reliability: 90, bias: -8, factChecking: 5, editorialStandards: 4, transparency: 5 },
    'nytimes.com': { reliability: 88, bias: -12, factChecking: 4, editorialStandards: 5, transparency: 4 },
    'wsj.com': { reliability: 87, bias: 8, factChecking: 4, editorialStandards: 5, transparency: 4 },
    
    // Left-leaning
    'cnn.com': { reliability: 75, bias: -20, factChecking: 3, editorialStandards: 3, transparency: 3 },
    'msnbc.com': { reliability: 72, bias: -25, factChecking: 3, editorialStandards: 3, transparency: 3 },
    'huffpost.com': { reliability: 70, bias: -22, factChecking: 3, editorialStandards: 3, transparency: 3 },
    'vox.com': { reliability: 73, bias: -18, factChecking: 3, editorialStandards: 4, transparency: 4 },
    
    // Right-leaning
    'foxnews.com': { reliability: 68, bias: 25, factChecking: 2, editorialStandards: 3, transparency: 3 },
    'nypost.com': { reliability: 65, bias: 20, factChecking: 2, editorialStandards: 3, transparency: 3 },
    'dailywire.com': { reliability: 60, bias: 28, factChecking: 2, editorialStandards: 2, transparency: 2 },
    
    // Low credibility
    'infowars.com': { reliability: 25, bias: 35, factChecking: 1, editorialStandards: 1, transparency: 1 },
    'naturalnews.com': { reliability: 20, bias: 15, factChecking: 1, editorialStandards: 1, transparency: 1 },
    'breitbart.com': { reliability: 30, bias: 32, factChecking: 1, editorialStandards: 2, transparency: 2 },
    'dailybuzzlive.com': { reliability: 15, bias: 0, factChecking: 1, editorialStandards: 1, transparency: 1 },
  
     // Highly trusted Indian sources
     'thehindu.com': { reliability: 90, bias: -5, factChecking: 4, editorialStandards: 5, transparency: 4 },
     'indianexpress.com': { reliability: 88, bias: -3, factChecking: 4, editorialStandards: 5, transparency: 4 },
     'hindustantimes.com': { reliability: 85, bias: -2, factChecking: 4, editorialStandards: 4, transparency: 4 },
     'livemint.com': { reliability: 84, bias: 0, factChecking: 4, editorialStandards: 4, transparency: 4 },
     'business-standard.com': { reliability: 83, bias: 0, factChecking: 4, editorialStandards: 4, transparency: 4 },
     'theprint.in': { reliability: 82, bias: -2, factChecking: 4, editorialStandards: 4, transparency: 4 },
   
     // Left-leaning Indian sources
     'scroll.in': { reliability: 72, bias: -15, factChecking: 3, editorialStandards: 3, transparency: 3 },
     'thewire.in': { reliability: 70, bias: -18, factChecking: 3, editorialStandards: 3, transparency: 3 },
     'newslaundry.com': { reliability: 68, bias: -20, factChecking: 3, editorialStandards: 3, transparency: 3 },
     'caravanmagazine.in': { reliability: 65, bias: -22, factChecking: 3, editorialStandards: 3, transparency: 3 },
     'altnews.in': { reliability: 75, bias: -10, factChecking: 4, editorialStandards: 4, transparency: 4 },
   
     // Right-leaning Indian sources
     'opindia.com': { reliability: 55, bias: 30, factChecking: 2, editorialStandards: 2, transparency: 2 },
     'swarajyamag.com': { reliability: 60, bias: 25, factChecking: 2, editorialStandards: 3, transparency: 3 },
     'republicworld.com': { reliability: 58, bias: 28, factChecking: 2, editorialStandards: 2, transparency: 2 },
     'timesnownews.com': { reliability: 62, bias: 20, factChecking: 3, editorialStandards: 3, transparency: 3 },
     'firstpost.com': { reliability: 65, bias: 18, factChecking: 3, editorialStandards: 3, transparency: 3 },
   
     // Low credibility Indian sources
    'postcard.news': { reliability: 20, bias: 30, factChecking: 1, editorialStandards: 1, transparency: 1 },
    'thedailystar.net': { reliability: 25, bias: 10, factChecking: 1, editorialStandards: 1, transparency: 1 },
    'indiatimes.com': { reliability: 30, bias: 5, factChecking: 2, editorialStandards: 2, transparency: 2 },
    'indiatvnews.com': { reliability: 35, bias: 10, factChecking: 2, editorialStandards: 2, transparency: 2 },
    'zeenews.india.com': { reliability: 40, bias: 15, factChecking: 2, editorialStandards: 2, transparency: 2 },
    'oneindia.com': { reliability: 25, bias: 5, factChecking: 1, editorialStandards: 1, transparency: 1 },
  
    // Academic and government domains
    'ugc.ac.in': { reliability: 85, bias: -5, factChecking: 4, editorialStandards: 4, transparency: 4 },
    'gov.in': { reliability: 80, bias: 0, factChecking: 4, editorialStandards: 4, transparency: 4 },
  
    // Suspicious domains
    'xyznews.com': { reliability: 30, bias: 0, factChecking: 1, editorialStandards: 1, transparency: 1 },
    'infoalerts.xyz': { reliability: 20, bias: 0, factChecking: 1, editorialStandards: 1, transparency: 1 },
    'clickbaitnews.top': { reliability: 15, bias: 0, factChecking: 1, editorialStandards: 1, transparency: 1 }
  
  };
module.exports={
    rightBiasWords,
    leftBiasWords,
    negativeWords,
    positiveWords,
    scientificWords,
    sensationalWords,
    stopWords,
    fakePhrases,
    sourceReputationData
};